
import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Inter } from 'next/font/google'

const inter = Inter({
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
      {children}
      </body>
    </html>
  );
}
